export const cardsData = [
  {
    tag: "new-house",
    image: "assets/images/house_cards/house_1.png",
    location: "Verdun, Montreal",
    bedrooms: 3,
    wifi: true,
    price: "200,000",
    timeframe: "anum",
    link: "#",
  },
  {
    tag: "popular",
    image: "assets/images/house_cards/house_2.png",
    location: "St Henri, Montreal",
    bedrooms: 2,
    wifi: true,
    price: "800,000",
    timeframe: "anum",
    link: "#",
  },
  {
    tag: "new-house",
    image: "assets/images/house_cards/house_3.png",
    location: "Downtown, Montreal",
    bedrooms: 3,
    wifi: true,
    price: "50,000",
    timeframe: "night",
    link: "#",
  },
  {
    image: "assets/images/house_cards/house_4.png",
    location: "Verdun, Montreal",
    bedrooms: 1,
    price: "200,000",
    timeframe: "night",
    link: "#",
  },
];
